---

- name: Update apt cache.
  apt: update_cache=yes

- name: Install apt-transport and ca-certificates
  apt: package={{ item }} state=present force=yes
  with_items:
  - apt-transport-https
  - lsb-release
  - ca-certificates

- name: Download sury gpg
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
    mode: 0644

- name: add sury to sourcelist
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/php.list
    regexp: 'packages\.sury\.org'
    state: present
    line: 'deb https://packages.sury.org/php/ stretch main'

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install php7-fpm
  apt: package={{ item }} state=present force=yes
  with_items:
  - php7.0-mbstring
  - php7.0-curl
  - php7.0-mysql
  - php7.0-opcache
  - php7.0-json
  - php7.0-xml
  - php7.0-common
  - php7.0-cli
  - php7.0-fpm
  - php7.0-cgi
  - php7.0-gd
  - php7.0-intl
  - php7.0-soap
  - php7.0-zip
  - php7.0-xmlrpc
  - libssl1.1
  - php-common
  - php-xdebug

- name: custom.ini and xdebug.ini
  copy: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
  - { src: 'custom.ini', dest: '/etc/php/7.0/mods-available/custom.ini'}
  - { src: 'xdebug.ini',  dest: '/etc/php/7.0/mods-available/xdebug.ini'}
  - { src: 'www.conf',  dest: '/etc/php/7.0/fpm/pool.d/www.conf'}

- name: enable php modules
  file: src="{{ item.src }}" dest="{{ item.dest }}" state="link"
  with_items:
  - { src: '/etc/php/7.0/mods-available/custom.ini', dest: '/etc/php/7.0/fpm/conf.d/20-custom.ini' }
  - { src: '/etc/php/7.0/mods-available/xdebug.ini', dest: '/etc/php/7.0/fpm/conf.d/20-xdebug.ini' }
  - { src: '/etc/php/7.0/mods-available/custom.ini', dest: '/etc/php/7.0/cli/conf.d/20-custom.ini' }
  - { src: '/etc/php/7.0/mods-available/xdebug.ini', dest: '/etc/php/7.0/cli/conf.d/20-xdebug.ini' }

- name: enable exceptions for NumberFormatter
  lineinfile:
    path: /etc/php/7.0/mods-available/intl.ini
    regexp: 'intl\.use_exceptions'
    state: present
    line: 'intl.use_exceptions=1'
