---

- name: Update apt cache.
  apt: update_cache=yes

- name: Install apt-transport and ca-certificates
  apt:
    package:
      - apt-transport-https
      - lsb-release
      - ca-certificates
    state: present
    force: yes

- name: Download sury gpg
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg
    mode: 0644

- name: add sury to sourcelist
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/php.list
    regexp: 'packages\.sury\.org'
    state: present
    line: 'deb https://packages.sury.org/php/ {{ansible_facts.distribution_release}} main'

- name: Update apt cache.
  apt: update_cache=yes

- name: 'Install php{{php_version}}'
  apt:
    package:
      - 'php{{php_version}}-mbstring'
      - 'php{{php_version}}-curl'
      - 'php{{php_version}}-mysql'
      - 'php{{php_version}}-opcache'
      - 'php{{php_version}}-json'
      - 'php{{php_version}}-xml'
      - 'php{{php_version}}-common'
      - 'php{{php_version}}-cli'
      - 'php{{php_version}}-fpm'
      - 'php{{php_version}}-cgi'
      - 'php{{php_version}}-gd'
      - 'php{{php_version}}-intl'
      - 'php{{php_version}}-soap'
      - 'php{{php_version}}-zip'
      - 'php{{php_version}}-xmlrpc'
      - 'php{{php_version}}-bcmath'
      - libssl1.1
      - php-imagick
      - php-common
      - php-xdebug
    state: present
    force: yes

- name: custom.ini and xdebug.ini
  copy: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
  - { src: 'custom.ini', dest: '/etc/php/{{php_version}}/mods-available/custom.ini'}
  - { src: 'xdebug.ini',  dest: '/etc/php/{{php_version}}/mods-available/xdebug.ini'}
  - { src: 'www.conf',  dest: '/etc/php/{{php_version}}/fpm/pool.d/www.conf'}

- name: enable php modules
  file: src="{{ item.src }}" dest="{{ item.dest }}" state="link"
  with_items:
  - { src: '/etc/php/{{php_version}}/mods-available/custom.ini', dest: '/etc/php/{{php_version}}/fpm/conf.d/20-custom.ini' }
  - { src: '/etc/php/{{php_version}}/mods-available/xdebug.ini', dest: '/etc/php/{{php_version}}/fpm/conf.d/20-xdebug.ini' }
  - { src: '/etc/php/{{php_version}}/mods-available/custom.ini', dest: '/etc/php/{{php_version}}/cli/conf.d/20-custom.ini' }
  - { src: '/etc/php/{{php_version}}/mods-available/xdebug.ini', dest: '/etc/php/{{php_version}}/cli/conf.d/20-xdebug.ini' }

- name: enable exceptions for NumberFormatter
  lineinfile:
    path: '/etc/php/{{php_version}}/mods-available/intl.ini'
    regexp: 'intl\.use_exceptions'
    state: present
    line: 'intl.use_exceptions=1'
