- hosts: localhost
  roles:
    - {role: dircolors, tags: 'dircolors'}
    - {role: directories, tags: 'directories'}
    - {role: sury-php7.0-7.4, tags: 'php', vars: {php_version: 7.0}}
    - {role: sury-php7.0-7.4, tags: 'php', vars: {php_version: 7.1}}
    - {role: sury-php7.0-7.4, tags: 'php', vars: {php_version: 7.2}}
    - {role: sury-php7.0-7.4, tags: 'php', vars: {php_version: 7.4}}
    - {role: composer, tags: composer, vars: {default_php_version: 7.1}}
    - {role: roles/libxl, tags: libxl}
