- hosts: localhost
  vars:
    my_user: fdekker
  roles:
    - {role: bashrc, tags: 'bashrc'}
    - {role: dircolors, tags: 'dircolors'}
    - {role: directories, tags: 'directories'}
    - {role: sury-php7.0-7.4, tags: 'php', vars: {php_version: 7.2}}
    - {role: sury-php7.0-7.4, tags: 'php', vars: {php_version: 7.4}}
    - {role: composer, tags: composer, vars: {default_php_version: 7.1}}
    - {role: roles/libsodium, tags: libsodium}
    - {role: roles/libxl, tags: libxl}
