- hosts: localhost
  roles:
    - roles/dircolors
    - role: sury-php7.0-7.4
      vars:
        php_version: 7.0
    - role: sury-php7.0-7.4
      vars:
        php_version: 7.1
    - role: sury-php7.0-7.4
      vars:
        php_version: 7.2
    - role: sury-php7.0-7.4
      vars:
        php_version: 7.4
    - role: composer
       vars:
         default_php_version: 7.1
    - roles/libxl
