---

- name: detect current version
  shell:  php{{libxl_php_version}} -i | grep "excel support" | cut -d ' ' -f4
  register: libxl_installed

- name: replace php version to {{libxl_php_version}}
  replace:
    path: /root/install_phpexcel_php7.sh
    regexp: 'PHP_VERSION=([0-9.]+)'
    replace: 'PHP_VERSION={{libxl_php_version}}'
  when: libxl_installed.stdout != 'enabled'

- name: install libxl for php {{libxl_php_version}}
  shell: /root/install_phpexcel_php7.sh
  when: libxl_installed.stdout != 'enabled'
