---
- name: Download dircolors from github
  get_url:
    url: https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/LS_COLORS
    dest: /etc/dircolors
    mode: '0444'

- name: add dircolors to /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: 'dircolors'
    line:  "eval $(dircolors -b /etc/dircolors)"
